import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { existsSync, mkdtempSync, rmSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { CertificateManager } from "../lib/certificate-manager.js";
import { ensureCerts } from "../lib/tls.js";

describe("CertificateManager", () => {
  describe("getNetworkIdForIp", () => {
    it("generates network ID from IP subnet", () => {
      const testDir = mkdtempSync(join(tmpdir(), "katulong-cert-mgr-test-"));
      try {
        const mgr = new CertificateManager(testDir, "Test");

        assert.equal(mgr.getNetworkIdForIp("192.168.1.100"), "net-192-168-1-0");
        assert.equal(mgr.getNetworkIdForIp("10.0.0.50"), "net-10-0-0-0");
        assert.equal(mgr.getNetworkIdForIp("172.16.5.200"), "net-172-16-5-0");
      } finally {
        rmSync(testDir, { recursive: true, force: true });
      }
    });

    it("returns 'default' for localhost IPs", () => {
      const testDir = mkdtempSync(join(tmpdir(), "katulong-cert-mgr-test-"));
      try {
        const mgr = new CertificateManager(testDir, "Test");

        assert.equal(mgr.getNetworkIdForIp("127.0.0.1"), "default");
        assert.equal(mgr.getNetworkIdForIp("::1"), "default");
        assert.equal(mgr.getNetworkIdForIp("localhost"), "default");
      } finally {
        rmSync(testDir, { recursive: true, force: true });
      }
    });
  });

  describe("initialize", () => {
    it("creates networks directory if it doesn't exist", async () => {
      const testDir = mkdtempSync(join(tmpdir(), "katulong-cert-mgr-test-"));
      try {
        // Ensure CA exists
        await ensureCerts(testDir, "Test");

        const mgr = new CertificateManager(testDir, "Test");
        await mgr.initialize();

        const networksDir = join(testDir, "tls", "networks");
        assert.ok(existsSync(networksDir), "Networks directory should be created");
      } finally {
        rmSync(testDir, { recursive: true, force: true });
      }
    });

    it("migrates single cert to default network", async () => {
      const testDir = mkdtempSync(join(tmpdir(), "katulong-cert-mgr-test-"));
      try {
        // Create old-style cert structure
        await ensureCerts(testDir, "Test");

        const oldCertPath = join(testDir, "tls", "server.crt");
        const oldKeyPath = join(testDir, "tls", "server.key");
        assert.ok(existsSync(oldCertPath), "Old cert should exist");

        // Initialize certificate manager
        const mgr = new CertificateManager(testDir, "Test");
        await mgr.initialize();

        // Check migration
        const defaultDir = join(testDir, "tls", "networks", "default");
        assert.ok(existsSync(defaultDir), "Default network directory should be created");
        assert.ok(existsSync(join(defaultDir, "server.crt")), "Default cert should exist");
        assert.ok(existsSync(join(defaultDir, "server.key")), "Default key should exist");
        assert.ok(existsSync(join(defaultDir, "metadata.json")), "Metadata should exist");

        // Check metadata
        const metadata = JSON.parse(readFileSync(join(defaultDir, "metadata.json"), "utf-8"));
        assert.equal(metadata.networkId, "default");
        assert.equal(metadata.label, "Default Network");
        assert.equal(metadata.autoGenerated, false);

        // Old files should still exist (not deleted for safety)
        assert.ok(existsSync(oldCertPath), "Old cert should still exist");
      } finally {
        rmSync(testDir, { recursive: true, force: true });
      }
    });

    it("loads all network certificates into cache", async () => {
      const testDir = mkdtempSync(join(tmpdir(), "katulong-cert-mgr-test-"));
      try {
        // Create CA
        await ensureCerts(testDir, "Test");

        const mgr = new CertificateManager(testDir, "Test");
        await mgr.initialize();

        // Auto-generate cert for a network
        await mgr.ensureNetworkCert("192.168.1.100");

        // Create new manager and initialize (should load from disk)
        const mgr2 = new CertificateManager(testDir, "Test");
        await mgr2.initialize();

        const networks = await mgr2.listNetworks();
        assert.ok(networks.length >= 1, "Should load networks from disk");

        const network = networks.find(n => n.networkId === "net-192-168-1-0");
        assert.ok(network, "Should load the generated network");
      } finally {
        rmSync(testDir, { recursive: true, force: true });
      }
    });
  });

  describe("ensureNetworkCert", () => {
    it("auto-generates cert for new network", async () => {
      const testDir = mkdtempSync(join(tmpdir(), "katulong-cert-mgr-test-"));
      try {
        // Create CA
        await ensureCerts(testDir, "Test");

        const mgr = new CertificateManager(testDir, "Test");
        await mgr.initialize();

        // Generate cert for new network
        const networkId = await mgr.ensureNetworkCert("192.168.1.100");

        assert.equal(networkId, "net-192-168-1-0");

        // Check files exist
        const networkDir = join(testDir, "tls", "networks", networkId);
        assert.ok(existsSync(join(networkDir, "server.crt")), "Network cert should exist");
        assert.ok(existsSync(join(networkDir, "server.key")), "Network key should exist");
        assert.ok(existsSync(join(networkDir, "metadata.json")), "Metadata should exist");

        // Check metadata
        const metadata = JSON.parse(readFileSync(join(networkDir, "metadata.json"), "utf-8"));
        assert.equal(metadata.networkId, networkId);
        assert.deepEqual(metadata.ips, ["192.168.1.100"]);
        assert.equal(metadata.autoGenerated, true);
      } finally {
        rmSync(testDir, { recursive: true, force: true });
      }
    });

    it("does not regenerate if cert already exists", async () => {
      const testDir = mkdtempSync(join(tmpdir(), "katulong-cert-mgr-test-"));
      try {
        await ensureCerts(testDir, "Test");

        const mgr = new CertificateManager(testDir, "Test");
        await mgr.initialize();

        // Generate cert
        await mgr.ensureNetworkCert("192.168.1.100");

        const networkDir = join(testDir, "tls", "networks", "net-192-168-1-0");
        const cert1 = readFileSync(join(networkDir, "server.crt"), "utf-8");

        // Wait a bit
        await new Promise(resolve => setTimeout(resolve, 100));

        // Try to ensure again
        await mgr.ensureNetworkCert("192.168.1.100");

        const cert2 = readFileSync(join(networkDir, "server.crt"), "utf-8");

        // Should be the same cert
        assert.equal(cert1, cert2, "Cert should not be regenerated");
      } finally {
        rmSync(testDir, { recursive: true, force: true });
      }
    });

    it("enforces maximum networks limit", async () => {
      const testDir = mkdtempSync(join(tmpdir(), "katulong-cert-mgr-test-"));
      try {
        await ensureCerts(testDir, "Test");

        const mgr = new CertificateManager(testDir, "Test");
        await mgr.initialize();

        // After initialization, we have 1 network (default from migration)
        // Generate 9 more networks to reach limit of 10
        for (let i = 1; i <= 9; i++) {
          await mgr.ensureNetworkCert(`192.168.${i}.100`);
        }

        // Try to generate 11th network
        await assert.rejects(
          async () => await mgr.ensureNetworkCert("192.168.99.100"),
          /Maximum of 10 networks reached/,
          "Should reject when max networks reached"
        );
      } finally {
        rmSync(testDir, { recursive: true, force: true });
      }
    });
  });

  describe("regenerateNetwork", () => {
    it("regenerates certificate for existing network", async () => {
      const testDir = mkdtempSync(join(tmpdir(), "katulong-cert-mgr-test-"));
      try {
        await ensureCerts(testDir, "Test");

        const mgr = new CertificateManager(testDir, "Test");
        await mgr.initialize();

        // Generate cert
        const networkId = await mgr.ensureNetworkCert("192.168.1.100");

        const networkDir = join(testDir, "tls", "networks", networkId);
        const cert1 = readFileSync(join(networkDir, "server.crt"), "utf-8");

        // Wait a bit
        await new Promise(resolve => setTimeout(resolve, 100));

        // Regenerate
        await mgr.regenerateNetwork(networkId);

        const cert2 = readFileSync(join(networkDir, "server.crt"), "utf-8");

        // Certs should be different
        assert.notEqual(cert1, cert2, "Cert should be regenerated");
      } finally {
        rmSync(testDir, { recursive: true, force: true });
      }
    });
  });

  describe("reloadCertificate", () => {
    it("hot-reloads certificate after regeneration", async () => {
      const testDir = mkdtempSync(join(tmpdir(), "katulong-cert-mgr-test-"));
      try {
        await ensureCerts(testDir, "Test");

        const mgr = new CertificateManager(testDir, "Test");
        await mgr.initialize();

        // Generate cert
        const networkId = await mgr.ensureNetworkCert("192.168.1.100");

        // Get context from cache
        const context1 = mgr.getSecureContext(networkId);

        // Regenerate cert
        await mgr.regenerateNetwork(networkId);

        // Reload certificate
        await mgr.reloadCertificate(networkId);

        // Get context again
        const context2 = mgr.getSecureContext(networkId);

        // Contexts should be different objects
        assert.notEqual(context1, context2, "Context should be reloaded");
      } finally {
        rmSync(testDir, { recursive: true, force: true });
      }
    });
  });

  describe("revokeNetwork", () => {
    it("deletes network certificate", async () => {
      const testDir = mkdtempSync(join(tmpdir(), "katulong-cert-mgr-test-"));
      try {
        await ensureCerts(testDir, "Test");

        const mgr = new CertificateManager(testDir, "Test");
        await mgr.initialize();

        // Generate cert
        const networkId = await mgr.ensureNetworkCert("192.168.1.100");

        const networkDir = join(testDir, "tls", "networks", networkId);
        assert.ok(existsSync(networkDir), "Network dir should exist");

        // Revoke
        await mgr.revokeNetwork(networkId);

        // Check removed
        assert.ok(!existsSync(networkDir), "Network dir should be deleted");

        const networks = await mgr.listNetworks();
        assert.ok(!networks.find(n => n.networkId === networkId), "Network should not be in list");
      } finally {
        rmSync(testDir, { recursive: true, force: true });
      }
    });

    it("prevents revoking default network", async () => {
      const testDir = mkdtempSync(join(tmpdir(), "katulong-cert-mgr-test-"));
      try {
        await ensureCerts(testDir, "Test");

        const mgr = new CertificateManager(testDir, "Test");
        await mgr.initialize();

        await assert.rejects(
          async () => await mgr.revokeNetwork("default"),
          /Cannot revoke default network/,
          "Should reject revoking default network"
        );
      } finally {
        rmSync(testDir, { recursive: true, force: true });
      }
    });
  });

  describe("updateNetworkLabel", () => {
    it("updates network label", async () => {
      const testDir = mkdtempSync(join(tmpdir(), "katulong-cert-mgr-test-"));
      try {
        await ensureCerts(testDir, "Test");

        const mgr = new CertificateManager(testDir, "Test");
        await mgr.initialize();

        // Generate cert
        const networkId = await mgr.ensureNetworkCert("192.168.1.100");

        // Update label
        await mgr.updateNetworkLabel(networkId, "Home Network");

        // Check metadata
        const networks = await mgr.listNetworks();
        const network = networks.find(n => n.networkId === networkId);
        assert.equal(network.label, "Home Network");
      } finally {
        rmSync(testDir, { recursive: true, force: true });
      }
    });
  });

  describe("listNetworks", () => {
    it("returns all networks sorted by lastUsedAt", async () => {
      const testDir = mkdtempSync(join(tmpdir(), "katulong-cert-mgr-test-"));
      try {
        await ensureCerts(testDir, "Test");

        const mgr = new CertificateManager(testDir, "Test");
        await mgr.initialize();

        // Generate multiple networks with delays
        await mgr.ensureNetworkCert("192.168.1.100");
        await new Promise(resolve => setTimeout(resolve, 10));
        await mgr.ensureNetworkCert("192.168.2.100");
        await new Promise(resolve => setTimeout(resolve, 10));
        await mgr.ensureNetworkCert("192.168.3.100");

        const networks = await mgr.listNetworks();

        assert.ok(networks.length >= 3, "Should have at least 3 networks");

        // Check sorted by lastUsedAt descending
        for (let i = 1; i < networks.length; i++) {
          const prev = new Date(networks[i - 1].lastUsedAt);
          const curr = new Date(networks[i].lastUsedAt);
          assert.ok(prev >= curr, "Networks should be sorted by lastUsedAt descending");
        }
      } finally {
        rmSync(testDir, { recursive: true, force: true });
      }
    });
  });

  describe("SNI callback", () => {
    it("returns certificate context for network", async () => {
      const testDir = mkdtempSync(join(tmpdir(), "katulong-cert-mgr-test-"));
      try {
        await ensureCerts(testDir, "Test");

        const mgr = new CertificateManager(testDir, "Test");
        await mgr.initialize();

        // Generate cert
        await mgr.ensureNetworkCert("192.168.1.100");

        const sniCallback = mgr.getSNICallback();

        // Call SNI callback
        await new Promise((resolve, reject) => {
          sniCallback("192.168.1.100", (err, context) => {
            if (err) reject(err);
            else {
              assert.ok(context, "Should return context");
              resolve();
            }
          });
        });
      } finally {
        rmSync(testDir, { recursive: true, force: true });
      }
    });

    it("auto-generates cert for new network on first access", async () => {
      const testDir = mkdtempSync(join(tmpdir(), "katulong-cert-mgr-test-"));
      try {
        await ensureCerts(testDir, "Test");

        const mgr = new CertificateManager(testDir, "Test");
        await mgr.initialize();

        const sniCallback = mgr.getSNICallback();

        // Call SNI callback for new IP
        await new Promise((resolve, reject) => {
          sniCallback("192.168.5.100", (err, context) => {
            if (err) reject(err);
            else {
              assert.ok(context, "Should return context");
              resolve();
            }
          });
        });

        // Check that network was auto-generated
        const networks = await mgr.listNetworks();
        const network = networks.find(n => n.networkId === "net-192-168-5-0");
        assert.ok(network, "Network should be auto-generated");
      } finally {
        rmSync(testDir, { recursive: true, force: true });
      }
    });
  });
});
