import { describe, it } from "node:test";
import assert from "node:assert";

/**
 * Test the ANSI sequences generated by the client-side term-update effect handler.
 * We extract the logic into a pure function for testing.
 */

function buildTermUpdateSequence(effect) {
  let seq = '';

  if (effect.action === 'scroll') {
    const rows = effect.termRows || 24;
    seq += `\x1b[${rows};1H`; // move to last row
    for (let i = 0; i < effect.count; i++) {
      seq += '\n'; // scroll up
    }
    // Write new lines at the bottom
    for (let i = 0; i < effect.newLines.length; i++) {
      const row = rows - effect.newLines.length + i + 1;
      seq += `\x1b[${row};1H\x1b[2K${effect.newLines[i]}`;
    }
  } else if (effect.action === 'mutations') {
    for (const row of effect.rows) {
      seq += `\x1b[${row.row + 1};1H\x1b[2K${row.content}`;
    }
  } else if (effect.action === 'full') {
    const lines = effect.lines || [];
    for (let i = 0; i < lines.length; i++) {
      seq += `\x1b[${i + 1};1H\x1b[2K${lines[i]}`;
    }
  }

  return seq;
}

describe("term-update ANSI sequence generation", () => {
  describe("scroll action", () => {
    it("generates newlines from bottom row for single scroll", () => {
      const seq = buildTermUpdateSequence({
        action: "scroll",
        count: 1,
        newLines: ["new content"],
        termRows: 4,
      });
      // Should: move to row 4, newline (scroll), then write "new content" at row 4
      assert.ok(seq.includes("\x1b[4;1H"), "moves to last row");
      assert.ok(seq.includes("\n"), "has newline for scroll");
      assert.ok(seq.includes("new content"), "has new content");
    });

    it("generates correct number of newlines for multi-scroll", () => {
      const seq = buildTermUpdateSequence({
        action: "scroll",
        count: 3,
        newLines: ["line1", "line2", "line3"],
        termRows: 10,
      });
      // Count newlines
      const newlineCount = (seq.match(/\n/g) || []).length;
      assert.strictEqual(newlineCount, 3, "should have 3 newlines for scroll count 3");
    });
  });

  describe("mutations action", () => {
    it("generates cursor positioning for each changed row", () => {
      const seq = buildTermUpdateSequence({
        action: "mutations",
        rows: [
          { row: 0, content: "first" },
          { row: 5, content: "sixth" },
        ],
      });
      assert.ok(seq.includes("\x1b[1;1H"), "positions at row 1");
      assert.ok(seq.includes("\x1b[6;1H"), "positions at row 6");
      assert.ok(seq.includes("first"), "has first row content");
      assert.ok(seq.includes("sixth"), "has sixth row content");
    });

    it("clears each line before writing", () => {
      const seq = buildTermUpdateSequence({
        action: "mutations",
        rows: [{ row: 2, content: "hello" }],
      });
      // \x1b[2K is "erase entire line"
      assert.ok(seq.includes("\x1b[2K"), "clears line before writing");
    });
  });

  describe("full action", () => {
    it("writes all lines with row positioning", () => {
      const seq = buildTermUpdateSequence({
        action: "full",
        lines: ["line1", "line2", "line3"],
      });
      assert.ok(seq.includes("\x1b[1;1H"), "positions at row 1");
      assert.ok(seq.includes("\x1b[2;1H"), "positions at row 2");
      assert.ok(seq.includes("\x1b[3;1H"), "positions at row 3");
      assert.ok(seq.includes("line1"), "has line1");
      assert.ok(seq.includes("line3"), "has line3");
    });
  });

  describe("edge cases", () => {
    it("handles empty lines in full action", () => {
      const seq = buildTermUpdateSequence({
        action: "full",
        lines: ["", "content", ""],
      });
      assert.ok(seq.includes("\x1b[2;1H\x1b[2Kcontent"), "writes content at row 2");
    });

    it("handles mutation with ANSI content", () => {
      const seq = buildTermUpdateSequence({
        action: "mutations",
        rows: [{ row: 0, content: "\x1b[32mgreen\x1b[0m" }],
      });
      assert.ok(seq.includes("\x1b[32mgreen\x1b[0m"), "preserves ANSI codes");
    });
  });
});
